name: Test SSL Version for Vercel API
on:
  push:
    branches:
      - main
jobs:
  Test-SSL-Version:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Check SSL Version for Vercel API
        run: |
          openssl s_client -connect api.vercel.com:443 -servername api.vercel.com
